--- 1. CREATE SEQUENCES ---
-- Đặt INCREMENT BY 50 để tối ưu cho Hibernate (khớp với allocationSize = 50)
CREATE SEQUENCE product_images_id_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE order_details_id_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE payments_id_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE idempotency_keys_id_seq START WITH 1 INCREMENT BY 50;

--- 2. TẠO TABLES (Sử dụng Sequence vừa tạo) ---

CREATE TABLE categories
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE roles
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE users
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    phone_number  VARCHAR(15)  NOT NULL UNIQUE,
    password      VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    address       VARCHAR(200),
    status        VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100)   NOT NULL UNIQUE,
    price         NUMERIC(19, 2) NOT NULL,
    status        VARCHAR(10),
    description   TEXT,
    thumbnail_url VARCHAR(200),
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    category_id   INT            NOT NULL,
    CONSTRAINT fk_prod_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE product_images
(
    id         INT PRIMARY KEY DEFAULT nextval('product_images_id_seq'),
    image_url  VARCHAR(300) NOT NULL,
    product_id BIGINT       NOT NULL,
    CONSTRAINT fk_img_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE inventories
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity          INTEGER       NOT NULL,
    reserved_quantity INTEGER       NOT NULL,
    sold_quantity     INTEGER       NOT NULL,
    version           BIGINT,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    product_id        BIGINT UNIQUE NOT NULL,
    CONSTRAINT fk_inv_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE orders
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_money       NUMERIC(19, 2) NOT NULL,
    recipient_name    VARCHAR(50)    NOT NULL,
    recipient_phone   VARCHAR(15)    NOT NULL,
    recipient_address VARCHAR(200)   NOT NULL,
    note              VARCHAR(200),
    status            VARCHAR(20)    NOT NULL,
    payment_method    VARCHAR(20)    NOT NULL,
    created_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id           BIGINT         NOT NULL,
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE order_details
(
    id                BIGINT PRIMARY KEY DEFAULT nextval('order_details_id_seq'),
    name              VARCHAR(100)   NOT NULL,
    quantity          INT            NOT NULL,
    price_at_purchase NUMERIC(19, 2) NOT NULL,
    order_id          BIGINT         NOT NULL,
    product_id        BIGINT         NOT NULL,
    CONSTRAINT fk_detail_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_detail_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE payments
(
    id             BIGINT PRIMARY KEY DEFAULT nextval('payments_id_seq'),
    transaction_id VARCHAR(50),
    method         VARCHAR(20)    NOT NULL,
    status         VARCHAR(20)    NOT NULL,
    amount         NUMERIC(19, 2) NOT NULL,
    bank_code      VARCHAR(50),
    card_type      VARCHAR(50),
    response_code  VARCHAR(20),
    failure_reason VARCHAR(100),
    metadata       TEXT,
    payment_time   TIMESTAMP,
    order_id       BIGINT         NOT NULL,
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE TABLE idempotency_keys
(
    id            BIGINT PRIMARY KEY DEFAULT nextval('idempotency_keys_id_seq'),
    key_id        VARCHAR(255) NOT NULL UNIQUE,
    response_body TEXT,
    status        VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMPTZ        DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ        DEFAULT CURRENT_TIMESTAMP
);

-- Bảng user_roles và refresh_tokens không cần sequence cho PK
-- vì dùng Composite Key hoặc UUID.
CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE refresh_tokens
(
    jti        UUID PRIMARY KEY,
    revoked    BOOLEAN     NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    user_id    BIGINT      NOT NULL,
    CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES users (id)
);
